apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<your aws account>:role/<your user account role>
      username: <your user account name>
      groups:
        - system:masters
    - rolearn: arn:aws:iam::<your aws account>:role/eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
